채팅 관련 entity mapping
DronicaPlatformService/droni-backend pull request #9
Opened 2024-04-08 07:40 UTC by blueRab2it

- message entity 구현
- message group entity 구현

2024-04-08 19:18 UTC, TaeTaeKim requested changes
그래도 entity mapping 바쁘신데 고생하셨습니다.

남기 리뷰들만 확인해주세요

2024-04-08 19:18 UTC, TaeTaeKim commented on src/main/java/droni/backend/message/dto/MessageGroupStatus.java
> +public enum MessageGroupStatus {
DroniServiceKind naming은 어떨까요?

Status는 상태인데 상태보다는 종류에 가까운거 같아서요

2024-04-08 19:18 UTC, TaeTaeKim commented on src/main/java/droni/backend/message/entity/Message.java
> +    private LocalDateTime deletedAt;
기획에서 메세지 delete랑 update는 빠질거 같아서 sql이랑 entity에서 모두 빼도 괜찮을거같아요

2024-04-08 19:18 UTC, TaeTaeKim commented on src/main/java/droni/backend/message/entity/Message.java
> +    private Boolean isPinned;
그리고 이거는 java에서 조금 꼬이는 부분인데

Lombok Getter라는 어노테이션이 getMethod를 만들때 타입이 boolean이면 getMethod 가 아닌 isMethod로 만들어요

그래서 isPinned면 Getter가 만드는 메소드랑 꼬여서 생성이 안되는 문제가 있어요 

private boolean pinned; 로 하고 jpa `@Column` 어노테이션 을 이용해서 매핑 시켜주는게 좋습니다

2024-04-08 19:32 UTC, TaeTaeKim commented on src/main/java/droni/backend/message/entity/Message.java
> +    private Boolean isPinned;
해당 부분 조금 더 찾아보니까 Boolean 이 아닌 `boolean` primitive Type 일 때 발생하는 문제라고 하네요.

Boolean 은 Null 이 들어올 수 있기 때문에 db의 is_pinned 컬럼에 null이 들어가길 원치 않는다면 초깃값 설정이 필요할 것 같아요

2024-04-08 19:49 UTC, blueRab2it commented on src/main/java/droni/backend/message/entity/Message.java
> +    private Boolean isPinned;
그렇다면 Boolean을 유지하고 default 값을 false로 할까요?

2024-04-09 03:15 UTC, TaeTaeKim commented on src/main/java/droni/backend/message/entity/Message.java
> +    private Boolean isPinned;
미미하지만 아무래도 Wrapper class 보다는 primitive type을 쓰는게 효율적입니다.

```java
@Column(name="is_pinned") @Builder.Default
private boolean pinned = false;
```

2024-04-09 03:17 UTC, TaeTaeKim commented
@blueRab2it 우영님 review resolve 권한 있으시죠? 코드 리뷰 끝난거는 resolve처리 직접하시면 될 거같아요

2024-04-10 03:26 UTC, TaeTaeKim approved these changes

2024-04-10 03:27 UTC, TaeTaeKim commented
고생하셨습니다

2024-04-11 07:55 UTC, merged